name: 部署 Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: wrangler 设置
    steps:
      - name: 设置账号
        uses: cloudflare/wrangler-action@v3.1.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: production
          workingDirectory:
          wranglerVersion: 3.25.0
          command: deployments
